name: tool_lab
description: "A multi-tool utility app with device sensors, calculator, and more."
publish_to: "none"
version: 1.4.0+16

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  go_router: ^17.3.0
  http: ^1.6.0
  file_selector: ^1.1.0
  share_plus: ^13.1.0
  sensors_plus: ^7.0.0
  device_info_plus: ^13.1.0
  battery_plus: ^7.0.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.4.0
  sqlite3: ^3.3.1
  path_provider: ^2.1.3
  path: ^1.9.0
  wakelock_plus: ^1.6.1
  flutter_soloud: ^4.0.6
  nfc_manager: ^4.2.1
  nfc_manager_ndef: ^1.1.0
  pdfrx: ^2.4.3
  pdfrx_engine: ^0.4.2
  desktop_drop: ^0.7.1
  flutter_markdown_plus: ^1.0.7
  url_launcher: ^6.3.0
  rhttp: ^0.18.0
  package_info_plus: ^10.1.0
  pdf: ^3.12.0
  markdown: ^7.3.1
  image: ^4.8.0
  image_picker: ^1.2.2
  pasteboard: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/google_fonts/

flutter_launcher_icons:
  android: true
  ios: false
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
  linux:
    generate: true
    image_path: "assets/logo/logo.png"
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#0B0F19"
  adaptive_icon_foreground: "assets/logo/logo.png"
